### ISSUE TITLE
[Bug] GitHub Action failed to commit initial pull request

### ISSUE THREAD

**Issue by Haseeb1604** [skills/review-pull-requests#22]
**GitHub Action Failed to commit Initial Pull Request**
When we create repository by clicking on "Use this Template" the default behaviour as per documentation a pull request must be automatically created from update-game branch and we then proceed towards next steps as  in instructions. but due to Failed in Initial steps we are unable to create any kind of listed action in this repository as the initial step failed to execute 

**To Reproduce**
1. Go to Repository
2. Click on "Use this template" and then click on create repository
3. wait for 20 sec so GitHub Action can automatically commit the changes
4. See error in GitHub Action, Step 0, Start

**Expected behavior**
Upon creating the repository and waiting for 20 sec upon successful creation of repository a pull request must be created from branch "update-game" to main branch

we have checked this behaviour from several accounts and devices but all the time results was same.

**Comment by roshan1337d** [comment]
@Haseeb1604 I have submitted a fix for this bug which is waiting to be approved and merged. Until then, you can follow the below steps as a workaround.

After creating your repository from the template,
1. Go to the settings tab of your repository
2. On the left menu, click Actions, then General.
3. Scroll down and "Allow GitHub Actions to create and approve pull requests", then save.
4. Now click the Actions Tab at the top of the screen and Click "Initial commit" (The one indicating an error)
5. On the left menu, click "Workflow file"
6. Edit the code at line 67 by adding a plus sign in front of "$BRANCH" so it should read "+$BRANCH"
7. Click Start Commit, then Commit changes
8. Refresh the page after about 20s and you are good to go!

A pull request will be created and you can proceed with the exercise. The steps in README file won't close and open automatically as it says there due to another bug, so you need to open them manually yourself.

**Comment by sinsukehlab** [comment]
Now that skills/action-update-step@v1.2.1 is released, the error is fixed.
I have also opened a PR #26 to fix the warning (deprecated Node.js).

**Comment by sinsukehlab** [comment]
There will be a new error if you create a repository from the template now due to restricted permissions.

https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
